package tables;
// Generated Mar 19, 2014 1:33:30 AM by Hibernate Tools 3.2.1.GA



/**
 * ContactUs generated by hbm2java
 */
public class ContactUs  implements java.io.Serializable {


     private String email;
     private String title;
     private String body;
     private String phone;
     private int read;

    public ContactUs() {
    }

	
    public ContactUs(String email, String body, String phone, int read) {
        this.email = email;
        this.body = body;
        this.phone = phone;
        this.read = read;
    }
    public ContactUs(String email, String title, String body, String phone, int read) {
       this.email = email;
       this.title = title;
       this.body = body;
       this.phone = phone;
       this.read = read;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public int getRead() {
        return this.read;
    }
    
    public void setRead(int read) {
        this.read = read;
    }




}


