package tables;
// Generated Mar 21, 2014 8:43:22 AM by Hibernate Tools 3.2.1.GA



/**
 * ContactUs generated by hbm2java
 */
public class ContactUs  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String body;
     private String phone;
     private int readornot;

    public ContactUs() {
    }

    public ContactUs(String email, String body, String phone, int readornot) {
       this.email = email;
       this.body = body;
       this.phone = phone;
       this.readornot = readornot;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public int getReadornot() {
        return this.readornot;
    }
    
    public void setReadornot(int readornot) {
        this.readornot = readornot;
    }




}


