package tables;
// Generated Mar 21, 2014 8:43:22 AM by Hibernate Tools 3.2.1.GA



/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer idProducts;
     private Categories categories;
     private String name;
     private String img;
     private int quantity;
     private int price;
     private String platform;
     private String description;

    public Products() {
    }

    public Products(Categories categories, String name, String img, int quantity, int price, String platform, String description) {
       this.categories = categories;
       this.name = name;
       this.img = img;
       this.quantity = quantity;
       this.price = price;
       this.platform = platform;
       this.description = description;
    }
   
    public Integer getIdProducts() {
        return this.idProducts;
    }
    
    public void setIdProducts(Integer idProducts) {
        this.idProducts = idProducts;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public String getPlatform() {
        return this.platform;
    }
    
    public void setPlatform(String platform) {
        this.platform = platform;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


