package tables;
// Generated Mar 21, 2014 8:43:22 AM by Hibernate Tools 3.2.1.GA



/**
 * ShoppingCart generated by hbm2java
 */
public class ShoppingCart  implements java.io.Serializable {


     private Integer idUserCart;
     private int productId;
     private String productName;
     private int userId;
     private int isPay;

    public ShoppingCart() {
    }

    public ShoppingCart(int productId, String productName, int userId, int isPay) {
       this.productId = productId;
       this.productName = productName;
       this.userId = userId;
       this.isPay = isPay;
    }
   
    public Integer getIdUserCart() {
        return this.idUserCart;
    }
    
    public void setIdUserCart(Integer idUserCart) {
        this.idUserCart = idUserCart;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getIsPay() {
        return this.isPay;
    }
    
    public void setIsPay(int isPay) {
        this.isPay = isPay;
    }




}


